/**
 * @format
 */

const { AppRegistry } = require('react-native');

const threadedRuntimeEnv = global.__THREADED_RUNTIME_ENV__;
const isListEnvironment =
  global._is_it_a_list_env === true && global.__COMPOSE_CHAT_LIST_ENV__;

if (threadedRuntimeEnv || isListEnvironment) {
  // Generated by the Metro wrapper from threadedComponent(...) exports.
  require('./.threaded-runtime/entry');

  if (threadedRuntimeEnv?.kind !== 'business-runtime') {
    AppRegistry.registerComponent(
      'ComposeChatSecondRuntimeRnList',
      () => require('./App').SecondRuntimeRnListApp,
    );
  }
}

const { name: appName } = require('./app.json');
AppRegistry.registerComponent(appName, () => require('./App').default);
