/**
 * @format
 */

const {AppRegistry} = require('react-native');

const isListEnvironment = global._is_it_a_list_env === true;

if (isListEnvironment) {
  // Generated by the Metro wrapper from threadedComponent(...) exports.
  require('./.threaded-runtime/entry');
  AppRegistry.registerComponent(
    'ComposeChatBackgroundRenderer',
    () => require('./src/chat/BackgroundChatRenderer').default,
  );
  AppRegistry.registerComponent(
    'ComposeChatSecondRuntimeRnList',
    () => require('./App').SecondRuntimeRnListApp,
  );
} else {
  const {name: appName} = require('./app.json');
  AppRegistry.registerComponent(appName, () => require('./App').default);
}
