const fs = require('fs');
const path = require('path');
const parser = require('@babel/parser');
const traverse = require('@babel/traverse').default;

const DEFAULT_EXTENSIONS = new Set(['.js', '.jsx', '.ts', '.tsx']);
const DEFAULT_IGNORED_DIRS = new Set([
  '.git',
  '.gradle',
  '.threaded-runtime',
  'android',
  'build',
  'ios',
  'node_modules',
]);

function withThreadedRuntime(config, options = {}) {
  const projectRoot = path.resolve(
    options.projectRoot || config.projectRoot || process.cwd(),
  );
  const generatedDir = path.resolve(
    projectRoot,
    options.generatedDir || '.threaded-runtime',
  );
  const generatedEntry = path.resolve(
    generatedDir,
    options.generatedEntry || 'entry.js',
  );

  generateThreadedRuntimeEntry({
    generatedEntry,
    projectRoot,
    roots: options.roots || ['App.tsx', 'src'],
  });

  return {
    ...config,
    watchFolders: Array.from(
      new Set([...(config.watchFolders || []), generatedDir]),
    ),
  };
}

function generateThreadedRuntimeEntry({
  generatedEntry,
  projectRoot = process.cwd(),
  roots = ['App.tsx', 'src'],
}) {
  const root = path.resolve(projectRoot);
  const files = collectSourceFiles(root, roots);
  const components = files.flatMap(file => scanThreadedComponents(file));
  const seenNames = new Map();

  components.forEach(component => {
    const existing = seenNames.get(component.name);
    if (existing) {
      throw new Error(
        `Duplicate threaded component name "${component.name}" in ` +
          `${component.file} and ${existing.file}`,
      );
    }
    seenNames.set(component.name, component);
  });

  components.sort((left, right) => left.name.localeCompare(right.name));

  const source = renderGeneratedEntry({
    components,
    generatedEntry,
    projectRoot: root,
  });
  fs.mkdirSync(path.dirname(generatedEntry), {recursive: true});
  if (
    !fs.existsSync(generatedEntry) ||
    fs.readFileSync(generatedEntry, 'utf8') !== source
  ) {
    fs.writeFileSync(generatedEntry, source);
  }

  return {
    components,
    generatedEntry,
  };
}

function collectSourceFiles(projectRoot, roots) {
  const files = [];

  roots.forEach(rootPath => {
    const absoluteRoot = path.resolve(projectRoot, rootPath);
    if (!fs.existsSync(absoluteRoot)) {
      return;
    }
    const stat = fs.statSync(absoluteRoot);
    if (stat.isFile()) {
      if (DEFAULT_EXTENSIONS.has(path.extname(absoluteRoot))) {
        files.push(absoluteRoot);
      }
      return;
    }
    if (stat.isDirectory()) {
      walkDirectory(absoluteRoot, files);
    }
  });

  return files.sort();
}

function walkDirectory(directory, files) {
  fs.readdirSync(directory, {withFileTypes: true}).forEach(entry => {
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      if (!DEFAULT_IGNORED_DIRS.has(entry.name)) {
        walkDirectory(absolutePath, files);
      }
      return;
    }

    if (entry.isFile() && DEFAULT_EXTENSIONS.has(path.extname(entry.name))) {
      files.push(absolutePath);
    }
  });
}

function scanThreadedComponents(file) {
  const source = fs.readFileSync(file, 'utf8');
  const ast = parser.parse(source, {
    errorRecovery: true,
    plugins: ['jsx', 'typescript'],
    sourceType: 'module',
  });
  const components = [];

  traverse(ast, {
    ExportNamedDeclaration(pathRef) {
      const declaration = pathRef.node.declaration;
      if (!declaration || declaration.type !== 'VariableDeclaration') {
        return;
      }

      declaration.declarations.forEach(declarator => {
        if (declarator.id.type !== 'Identifier') {
          return;
        }
        if (!isThreadedComponentCall(declarator.init)) {
          return;
        }
        const nameNode = declarator.init.arguments[0];
        if (!nameNode || nameNode.type !== 'StringLiteral') {
          throw new Error(
            `threadedComponent export ${declarator.id.name} in ${file} ` +
              'must use a string literal name',
          );
        }

        components.push({
          exportName: declarator.id.name,
          file,
          name: nameNode.value,
        });
      });
    },
  });

  return components;
}

function isThreadedComponentCall(node) {
  if (!node || node.type !== 'CallExpression') {
    return false;
  }
  const callee = node.callee;
  return callee.type === 'Identifier' && callee.name === 'threadedComponent';
}

function renderGeneratedEntry({components, generatedEntry, projectRoot}) {
  const generatedDir = path.dirname(generatedEntry);
  const registrations = components
    .map(component => {
      const requestPath = toRequirePath(generatedDir, component.file);
      return (
        `registerLazyThreadedComponent(${JSON.stringify(
          component.name,
        )}, () =>\n` +
        `  require(${JSON.stringify(requestPath)}).${component.exportName},\n` +
        ');'
      );
    })
    .join('\n\n');

  return (
    `// @generated by @native-compose/threaded-runtime/metro\n` +
    `// projectRoot: ${toPosixPath(projectRoot)}\n` +
    `import {AppRegistry} from 'react-native';\n` +
    `import {\n` +
    `  ThreadedRuntimeHost,\n` +
    `  registerLazyThreadedComponent,\n` +
    `} from '@native-compose/threaded-runtime';\n\n` +
    `${registrations}\n\n` +
    `AppRegistry.registerComponent('ThreadedRuntimeHost', () => ThreadedRuntimeHost);\n`
  );
}

function toRequirePath(fromDirectory, file) {
  const withoutExtension = file.slice(0, -path.extname(file).length);
  let relativePath = toPosixPath(
    path.relative(fromDirectory, withoutExtension),
  );
  if (!relativePath.startsWith('.')) {
    relativePath = `./${relativePath}`;
  }
  return relativePath;
}

function toPosixPath(value) {
  return value.split(path.sep).join('/');
}

module.exports = {
  generateThreadedRuntimeEntry,
  withThreadedRuntime,
};
